# Endereço local: http://localhost:3333/

POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Video 04",
    "description": "Esse é o quarto video",
    "duration": 180
}

###

# GET http://localhost:3333/videos?search=node
GET http://localhost:3333/videos
###

PUT http://localhost:3333/videos/6ba6f3b5-7c0f-4587-92c1-605df416716f
Content-Type: application/json

{
    "title": "Video 04",
    "description": "Esse é o quarto video",
    "duration": 80
}

###

DELETE http://localhost:3333/videos/6ba6f3b5-7c0f-4587-92c1-605df416716f
